import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './sidebar-hover.css';
import { Toaster } from 'react-hot-toast';
import { KanbanProvider } from './components/kanban/KanbanContext';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '600'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <KanbanProvider>{children}</KanbanProvider>
        <Toaster />
      </body>
    </html>
  );
}
